export const actionType = {
    FETCH_COMPANY_DATA_SUCCESS : "FETCH_COMPANY_DATA_SUCCESS",
    FETCH_COMPANY_DATA_FAILURE : "FETCH_COMPANY_DATA_FAILURE",
    FETCH_COMPANY_DATA_LOADING : "FETCH_COMPANY_DATA_LOADING",
    ADD_COMPANY : "ADD_COMPANY",
    UPDATE_COMPANY : "UPDATE_COMPANY",
    DELETE_COMPANY : "DELETE_COMPANY"
  };